import jsPDF from 'jspdf';
import { AnalysisResult, EEGData } from './eeg-processing';

interface ReportData {
  module: string;
  subjectName: string;
  details: Record<string, string>;
  eegData: EEGData;
  result: AnalysisResult;
  recommendations: string[];
  notes?: string;
}

export function generatePDFReport(data: ReportData): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(0, 200, 160);
  doc.text('NeuroInsight AI', margin, y);
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(150, 150, 150);
  doc.text(`${data.module} Analysis Report`, margin, y);
  y += 4;
  doc.setDrawColor(0, 200, 160);
  doc.line(margin, y, 190, y);
  y += 12;

  // Subject Details
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Subject Details', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  
  Object.entries(data.details).forEach(([key, value]) => {
    doc.text(`${key}: ${value}`, margin + 4, y);
    y += 6;
  });
  y += 6;

  // EEG Signal Data
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Signal Analysis', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Alpha (Relaxation): ${data.eegData.alpha} µV`, margin + 4, y); y += 6;
  doc.text(`Beta (Focus): ${data.eegData.beta} µV`, margin + 4, y); y += 6;
  doc.text(`Gamma (Cognition): ${data.eegData.gamma} µV`, margin + 4, y); y += 6;
  doc.text(`Theta (Drowsiness): ${data.eegData.theta} µV`, margin + 4, y); y += 10;

  // Results
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Analysis Results', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Focus Level: ${data.result.focusLevel}%`, margin + 4, y); y += 6;
  doc.text(`Stress Level: ${data.result.stressLevel}`, margin + 4, y); y += 6;
  doc.text(`Mental Fatigue: ${data.result.mentalFatigue}`, margin + 4, y); y += 6;
  doc.text(`Cognitive Load: ${data.result.cognitiveLoad}`, margin + 4, y); y += 10;

  // Recommendations
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Recommendations', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  data.recommendations.forEach((rec, i) => {
    if (y > 270) { doc.addPage(); y = margin; }
    doc.text(`${i + 1}. ${rec}`, margin + 4, y);
    y += 6;
  });

  if (data.notes) {
    y += 6;
    doc.setFontSize(14);
    doc.setTextColor(40, 40, 40);
    doc.text('Notes', margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(data.notes, 166);
    doc.text(lines, margin + 4, y);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by NeuroInsight AI • ${new Date().toLocaleString()}`, margin, 285);

  doc.save(`NeuroInsight_${data.module}_${data.subjectName.replace(/\s+/g, '_')}.pdf`);
}
